# 项目相关配置
ruoyi:
  # 名称
  name: XRobot
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 20000
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 数据源配置
spring:
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  200MB
      # 设置总上传的文件大小
      max-request-size:  300MB
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
    password: cwl19910230
  application:
    name: fairy-XRobot-server
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌有效期（默认60分钟）
  expireTime: 60
  loginExpireTime: 1440

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /xrobot/notice/*
  # 匹配链接
  urlPatterns: /xrobot/*,/monitor/*,/tool/*