package com.fairyland.xrobot.modular.xrobot.dao.mapper;

import com.fairyland.xrobot.modular.xrobot.domain.CreateGroups;
import com.fairyland.xrobot.modular.xrobot.domain.CreateGroupsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CreateGroupsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_creategroups
     *
     * @mbggenerated
     */
    int countByExample(CreateGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_creategroups
     *
     * @mbggenerated
     */
    int deleteByExample(CreateGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_creategroups
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_creategroups
     *
     * @mbggenerated
     */
    int insert(CreateGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_creategroups
     *
     * @mbggenerated
     */
    int insertSelective(CreateGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_creategroups
     *
     * @mbggenerated
     */
    List<CreateGroups> selectByExample(CreateGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_creategroups
     *
     * @mbggenerated
     */
    CreateGroups selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_creategroups
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CreateGroups record, @Param("example") CreateGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_creategroups
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CreateGroups record, @Param("example") CreateGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_creategroups
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CreateGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_creategroups
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CreateGroups record);
}