package com.fairyland.xrobot.modular.xrobot.dao.mapper;

import com.fairyland.xrobot.modular.xrobot.domain.TaskDevicesLog;
import com.fairyland.xrobot.modular.xrobot.domain.TaskDevicesLogExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TaskDevicesLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_taskdeviceslog
     *
     * @mbggenerated
     */
    int countByExample(TaskDevicesLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_taskdeviceslog
     *
     * @mbggenerated
     */
    int deleteByExample(TaskDevicesLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_taskdeviceslog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_taskdeviceslog
     *
     * @mbggenerated
     */
    int insert(TaskDevicesLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_taskdeviceslog
     *
     * @mbggenerated
     */
    int insertSelective(TaskDevicesLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_taskdeviceslog
     *
     * @mbggenerated
     */
    List<TaskDevicesLog> selectByExample(TaskDevicesLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_taskdeviceslog
     *
     * @mbggenerated
     */
    TaskDevicesLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_taskdeviceslog
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TaskDevicesLog record, @Param("example") TaskDevicesLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_taskdeviceslog
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TaskDevicesLog record, @Param("example") TaskDevicesLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_taskdeviceslog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TaskDevicesLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_taskdeviceslog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TaskDevicesLog record);

    void insertTasksDevicesLog(Map<String, Object> dbParams);
}