package com.fairyland.xrobot.modular.xrobot.dao.mapper;

import com.fairyland.xrobot.modular.xrobot.domain.Wsurls;
import com.fairyland.xrobot.modular.xrobot.domain.WsurlsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WsurlsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsurls
     *
     * @mbggenerated
     */
    int countByExample(WsurlsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsurls
     *
     * @mbggenerated
     */
    int deleteByExample(WsurlsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsurls
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsurls
     *
     * @mbggenerated
     */
    int insert(Wsurls record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsurls
     *
     * @mbggenerated
     */
    int insertSelective(Wsurls record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsurls
     *
     * @mbggenerated
     */
    List<Wsurls> selectByExampleWithBLOBs(WsurlsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsurls
     *
     * @mbggenerated
     */
    List<Wsurls> selectByExample(WsurlsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsurls
     *
     * @mbggenerated
     */
    Wsurls selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsurls
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Wsurls record, @Param("example") WsurlsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsurls
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Wsurls record, @Param("example") WsurlsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsurls
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Wsurls record, @Param("example") WsurlsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsurls
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Wsurls record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsurls
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Wsurls record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsurls
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Wsurls record);
}