package com.fairyland.xrobot.modular.xrobot.dao.mapper;

import com.fairyland.xrobot.modular.xrobot.domain.Groupnameinfo;
import com.fairyland.xrobot.modular.xrobot.domain.Wsusernumbers;
import com.fairyland.xrobot.modular.xrobot.domain.WsusernumbersExample;
import java.util.List;
import java.util.Map;

import com.fairyland.xrobot.modular.xrobot.domain.req.GroupnameListReq;
import com.fairyland.xrobot.modular.xrobot.domain.req.UserNumberListReq;
import com.fairyland.xrobot.modular.xrobot.domain.resp.ExportUserNumberListResp;
import com.fairyland.xrobot.modular.xrobot.domain.resp.UserNumberListResp;
import org.apache.ibatis.annotations.Param;

public interface WsusernumbersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsusernumbers
     *
     * @mbggenerated
     */
    int countByExample(WsusernumbersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsusernumbers
     *
     * @mbggenerated
     */
    int deleteByExample(WsusernumbersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsusernumbers
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsusernumbers
     *
     * @mbggenerated
     */
    int insert(Wsusernumbers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsusernumbers
     *
     * @mbggenerated
     */
    int insertSelective(Wsusernumbers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsusernumbers
     *
     * @mbggenerated
     */
    List<Wsusernumbers> selectByExampleWithBLOBs(WsusernumbersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsusernumbers
     *
     * @mbggenerated
     */
    List<Wsusernumbers> selectByExample(WsusernumbersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsusernumbers
     *
     * @mbggenerated
     */
    Wsusernumbers selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsusernumbers
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Wsusernumbers record, @Param("example") WsusernumbersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsusernumbers
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Wsusernumbers record, @Param("example") WsusernumbersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsusernumbers
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Wsusernumbers record, @Param("example") WsusernumbersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsusernumbers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Wsusernumbers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsusernumbers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Wsusernumbers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wsusernumbers
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Wsusernumbers record);

    List<ExportUserNumberListResp> exportUserNumberList();

    List<Wsusernumbers> userNumberList(UserNumberListReq paramReq);

    Integer getAllUserNumberCount();

    Integer getuserNumberCount();

    void userNumberClear();

    void batchInsertWsusernumber(Map<String, Object> dbParams);
}