package com.fairyland.xrobot.modular.xrobot.domain;

import com.fairyland.xrobot.common.utils.StringUtils;

public class AppVersion extends BaseEntity {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.osname
     *
     * @mbggenerated
     */
    private String osname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.context
     *
     * @mbggenerated
     */
    private String context;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.forceFlag
     *
     * @mbggenerated
     */
    private String forceflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.appversion
     *
     * @mbggenerated
     */
    private String appversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.downloadurl
     *
     * @mbggenerated
     */
    private String downloadurl;

    private String voDownloadurl;

    private String qrcode;

    public String getVoDownloadurl() {

        if (StringUtils.isNotEmpty(downloadurl)) {
            return "http://39.99.233.24:20001" + downloadurl;
            //return "http://148.66.129.158:20001" + downloadurl;
        }

        return voDownloadurl;
    }

    public void setVoDownloadurl(String voDownloadurl) {
        this.voDownloadurl = voDownloadurl;
    }

    public String getQrcode() {
        return qrcode;
    }

    public void setQrcode(String qrcode) {
        this.qrcode = qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.osname
     *
     * @return the value of app_version.osname
     * @mbggenerated
     */
    public String getOsname() {
        return osname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.osname
     *
     * @param osname the value for app_version.osname
     * @mbggenerated
     */
    public void setOsname(String osname) {
        this.osname = osname == null ? null : osname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.context
     *
     * @return the value of app_version.context
     * @mbggenerated
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.context
     *
     * @param context the value for app_version.context
     * @mbggenerated
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.title
     *
     * @return the value of app_version.title
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.title
     *
     * @param title the value for app_version.title
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.forceFlag
     *
     * @return the value of app_version.forceFlag
     * @mbggenerated
     */
    public String getForceflag() {
        return forceflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.forceFlag
     *
     * @param forceflag the value for app_version.forceFlag
     * @mbggenerated
     */
    public void setForceflag(String forceflag) {
        this.forceflag = forceflag == null ? null : forceflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.appversion
     *
     * @return the value of app_version.appversion
     * @mbggenerated
     */
    public String getAppversion() {
        return appversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.appversion
     *
     * @param appversion the value for app_version.appversion
     * @mbggenerated
     */
    public void setAppversion(String appversion) {
        this.appversion = appversion == null ? null : appversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.downloadurl
     *
     * @return the value of app_version.downloadurl
     * @mbggenerated
     */
    public String getDownloadurl() {
        return downloadurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.downloadurl
     *
     * @param downloadurl the value for app_version.downloadurl
     * @mbggenerated
     */
    public void setDownloadurl(String downloadurl) {
        this.downloadurl = downloadurl == null ? null : downloadurl.trim();
    }

}