package com.fairyland.xrobot.modular.xrobot.domain;

import com.fairyland.xrobot.common.constant.XRobotCode;
import com.fairyland.xrobot.modular.system.domain.SysUser;
import com.fairyland.xrobot.modular.xrobot.utils.Utility;
import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

/**
 * @program: fairyland->BaseEntity
 * @description: TODO
 * @author: ctc
 * @create: 2020-05-24 18:24
 **/
public class BaseEntity {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.create_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.update_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.id
     *
     * @return the value of c_device.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.id
     *
     * @param id the value for c_device.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.create_by
     *
     * @return the value of c_device.create_by
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.create_by
     *
     * @param createBy the value for c_device.create_by
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.create_date
     *
     * @return the value of c_device.create_date
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.create_date
     *
     * @param createDate the value for c_device.create_date
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.update_by
     *
     * @return the value of c_device.update_by
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.update_by
     *
     * @param updateBy the value for c_device.update_by
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.update_date
     *
     * @return the value of c_device.update_date
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.update_date
     *
     * @param updateDate the value for c_device.update_date
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.remarks
     *
     * @return the value of c_device.remarks
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.remarks
     *
     * @param remarks the value for c_device.remarks
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.del_flag
     *
     * @return the value of c_device.del_flag
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.del_flag
     *
     * @param delFlag the value for c_device.del_flag
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }


    public void preUpdate(SysUser user) {

        setUpdateBy(user.getUserName());

        setUpdateDate(Utility.getNowDate());
    }

    public void preUpdate(String userName) {

        setUpdateBy(userName);

        setUpdateDate(Utility.getNowDate());
    }

    public void preInsert(SysUser user) {

        setCreateBy(user.getUserName());
        setCreateDate(Utility.getNowDate());

        setUpdateBy(getCreateBy());

        setUpdateDate(getCreateDate());

        setDelFlag(XRobotCode.DEL_0);

    }

    public void preInsert(String userName) {

        setCreateBy(userName);
        setCreateDate(Utility.getNowDate());

        setUpdateBy(getCreateBy());

        setUpdateDate(getCreateDate());

        setDelFlag(XRobotCode.DEL_0);

    }
}
