package com.fairyland.xrobot.modular.xrobot.domain;

import java.util.Date;

public class Device {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.deviceID
     *
     * @mbggenerated
     */
    private String deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.deviceSN
     *
     * @mbggenerated
     */
    private String devicesn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.login
     *
     * @mbggenerated
     */
    private Byte login;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.account1
     *
     * @mbggenerated
     */
    private String account1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.password1
     *
     * @mbggenerated
     */
    private String password1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.login1
     *
     * @mbggenerated
     */
    private Byte login1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.state
     *
     * @mbggenerated
     */
    private Byte state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.id
     *
     * @return the value of c_device.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.id
     *
     * @param id the value for c_device.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.create_by
     *
     * @return the value of c_device.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.create_by
     *
     * @param createBy the value for c_device.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.create_date
     *
     * @return the value of c_device.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.create_date
     *
     * @param createDate the value for c_device.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.update_by
     *
     * @return the value of c_device.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.update_by
     *
     * @param updateBy the value for c_device.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.update_date
     *
     * @return the value of c_device.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.update_date
     *
     * @param updateDate the value for c_device.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.remarks
     *
     * @return the value of c_device.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.remarks
     *
     * @param remarks the value for c_device.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.del_flag
     *
     * @return the value of c_device.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.del_flag
     *
     * @param delFlag the value for c_device.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.deviceID
     *
     * @return the value of c_device.deviceID
     *
     * @mbggenerated
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.deviceID
     *
     * @param deviceid the value for c_device.deviceID
     *
     * @mbggenerated
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid == null ? null : deviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.deviceSN
     *
     * @return the value of c_device.deviceSN
     *
     * @mbggenerated
     */
    public String getDevicesn() {
        return devicesn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.deviceSN
     *
     * @param devicesn the value for c_device.deviceSN
     *
     * @mbggenerated
     */
    public void setDevicesn(String devicesn) {
        this.devicesn = devicesn == null ? null : devicesn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.token
     *
     * @return the value of c_device.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.token
     *
     * @param token the value for c_device.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.phone
     *
     * @return the value of c_device.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.phone
     *
     * @param phone the value for c_device.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.account
     *
     * @return the value of c_device.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.account
     *
     * @param account the value for c_device.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.password
     *
     * @return the value of c_device.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.password
     *
     * @param password the value for c_device.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.login
     *
     * @return the value of c_device.login
     *
     * @mbggenerated
     */
    public Byte getLogin() {
        return login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.login
     *
     * @param login the value for c_device.login
     *
     * @mbggenerated
     */
    public void setLogin(Byte login) {
        this.login = login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.account1
     *
     * @return the value of c_device.account1
     *
     * @mbggenerated
     */
    public String getAccount1() {
        return account1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.account1
     *
     * @param account1 the value for c_device.account1
     *
     * @mbggenerated
     */
    public void setAccount1(String account1) {
        this.account1 = account1 == null ? null : account1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.password1
     *
     * @return the value of c_device.password1
     *
     * @mbggenerated
     */
    public String getPassword1() {
        return password1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.password1
     *
     * @param password1 the value for c_device.password1
     *
     * @mbggenerated
     */
    public void setPassword1(String password1) {
        this.password1 = password1 == null ? null : password1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.login1
     *
     * @return the value of c_device.login1
     *
     * @mbggenerated
     */
    public Byte getLogin1() {
        return login1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.login1
     *
     * @param login1 the value for c_device.login1
     *
     * @mbggenerated
     */
    public void setLogin1(Byte login1) {
        this.login1 = login1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.state
     *
     * @return the value of c_device.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.state
     *
     * @param state the value for c_device.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }
}