package com.fairyland.xrobot.modular.xrobot.domain;

public class Device extends BaseEntity {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.deviceID
     *
     * @mbggenerated
     */
    private String deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.deviceSN
     *
     * @mbggenerated
     */
    private String devicesn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.login
     *
     * @mbggenerated
     */
    private Integer login;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.account1
     *
     * @mbggenerated
     */
    private String account1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.password1
     *
     * @mbggenerated
     */
    private String password1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.login1
     *
     * @mbggenerated
     */
    private Integer login1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_device.state
     *
     * @mbggenerated
     */
    private Integer state;

    private Integer allow;

    public Integer getAllow() {
        return allow;
    }

    public void setAllow(Integer allow) {
        this.allow = allow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.deviceID
     *
     * @return the value of c_device.deviceID
     * @mbggenerated
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.deviceID
     *
     * @param deviceid the value for c_device.deviceID
     * @mbggenerated
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid == null ? null : deviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.deviceSN
     *
     * @return the value of c_device.deviceSN
     * @mbggenerated
     */
    public String getDevicesn() {
        return devicesn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.deviceSN
     *
     * @param devicesn the value for c_device.deviceSN
     * @mbggenerated
     */
    public void setDevicesn(String devicesn) {
        this.devicesn = devicesn == null ? null : devicesn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.token
     *
     * @return the value of c_device.token
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.token
     *
     * @param token the value for c_device.token
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.phone
     *
     * @return the value of c_device.phone
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.phone
     *
     * @param phone the value for c_device.phone
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.account
     *
     * @return the value of c_device.account
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.account
     *
     * @param account the value for c_device.account
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.password
     *
     * @return the value of c_device.password
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.password
     *
     * @param password the value for c_device.password
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.login
     *
     * @return the value of c_device.login
     * @mbggenerated
     */
    public Integer getLogin() {
        return login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.login
     *
     * @param login the value for c_device.login
     * @mbggenerated
     */
    public void setLogin(Integer login) {
        this.login = login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.account1
     *
     * @return the value of c_device.account1
     * @mbggenerated
     */
    public String getAccount1() {
        return account1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.account1
     *
     * @param account1 the value for c_device.account1
     * @mbggenerated
     */
    public void setAccount1(String account1) {
        this.account1 = account1 == null ? null : account1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.password1
     *
     * @return the value of c_device.password1
     * @mbggenerated
     */
    public String getPassword1() {
        return password1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.password1
     *
     * @param password1 the value for c_device.password1
     * @mbggenerated
     */
    public void setPassword1(String password1) {
        this.password1 = password1 == null ? null : password1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.login1
     *
     * @return the value of c_device.login1
     * @mbggenerated
     */
    public Integer getLogin1() {
        return login1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.login1
     *
     * @param login1 the value for c_device.login1
     * @mbggenerated
     */
    public void setLogin1(Integer login1) {
        this.login1 = login1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_device.state
     *
     * @return the value of c_device.state
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_device.state
     *
     * @param state the value for c_device.state
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }


    private boolean monitorClientStatus;  // 客户端连接是否正常   true 连接中，false 未连接

    private String monitorClientAppStatus; // 监控 客户端app的状态

    private String monitorClientAppStatusCode; // 监控 客户端app的状态

    public boolean isMonitorClientStatus() {
        return monitorClientStatus;
    }

    public void setMonitorClientStatus(boolean monitorClientStatus) {
        this.monitorClientStatus = monitorClientStatus;
    }

    public String getMonitorClientAppStatus() {
        return monitorClientAppStatus;
    }

    public void setMonitorClientAppStatus(String monitorClientAppStatus) {
        this.monitorClientAppStatus = monitorClientAppStatus;
    }

    public String getMonitorClientAppStatusCode() {
        return monitorClientAppStatusCode;
    }

    public void setMonitorClientAppStatusCode(String monitorClientAppStatusCode) {
        this.monitorClientAppStatusCode = monitorClientAppStatusCode;
    }
}