package com.fairyland.xrobot.modular.xrobot.domain;

import java.util.Date;

public class DeviceGroupMembers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_devicegroupmembers.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_devicegroupmembers.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_devicegroupmembers.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_devicegroupmembers.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_devicegroupmembers.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_devicegroupmembers.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_devicegroupmembers.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_devicegroupmembers.groupID
     *
     * @mbggenerated
     */
    private String groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_devicegroupmembers.deviceID
     *
     * @mbggenerated
     */
    private String deviceid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_devicegroupmembers.id
     *
     * @return the value of c_devicegroupmembers.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_devicegroupmembers.id
     *
     * @param id the value for c_devicegroupmembers.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_devicegroupmembers.create_by
     *
     * @return the value of c_devicegroupmembers.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_devicegroupmembers.create_by
     *
     * @param createBy the value for c_devicegroupmembers.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_devicegroupmembers.create_date
     *
     * @return the value of c_devicegroupmembers.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_devicegroupmembers.create_date
     *
     * @param createDate the value for c_devicegroupmembers.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_devicegroupmembers.update_by
     *
     * @return the value of c_devicegroupmembers.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_devicegroupmembers.update_by
     *
     * @param updateBy the value for c_devicegroupmembers.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_devicegroupmembers.update_date
     *
     * @return the value of c_devicegroupmembers.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_devicegroupmembers.update_date
     *
     * @param updateDate the value for c_devicegroupmembers.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_devicegroupmembers.remarks
     *
     * @return the value of c_devicegroupmembers.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_devicegroupmembers.remarks
     *
     * @param remarks the value for c_devicegroupmembers.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_devicegroupmembers.del_flag
     *
     * @return the value of c_devicegroupmembers.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_devicegroupmembers.del_flag
     *
     * @param delFlag the value for c_devicegroupmembers.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_devicegroupmembers.groupID
     *
     * @return the value of c_devicegroupmembers.groupID
     *
     * @mbggenerated
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_devicegroupmembers.groupID
     *
     * @param groupid the value for c_devicegroupmembers.groupID
     *
     * @mbggenerated
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_devicegroupmembers.deviceID
     *
     * @return the value of c_devicegroupmembers.deviceID
     *
     * @mbggenerated
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_devicegroupmembers.deviceID
     *
     * @param deviceid the value for c_devicegroupmembers.deviceID
     *
     * @mbggenerated
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid == null ? null : deviceid.trim();
    }
}