package com.fairyland.xrobot.modular.xrobot.domain;

public class DeviceGroupMembers extends BaseEntity {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_devicegroupmembers.groupID
     *
     * @mbggenerated
     */
    private String groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_devicegroupmembers.deviceID
     *
     * @mbggenerated
     */
    private String deviceid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_devicegroupmembers.groupID
     *
     * @return the value of c_devicegroupmembers.groupID
     * @mbggenerated
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_devicegroupmembers.groupID
     *
     * @param groupid the value for c_devicegroupmembers.groupID
     * @mbggenerated
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_devicegroupmembers.deviceID
     *
     * @return the value of c_devicegroupmembers.deviceID
     * @mbggenerated
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_devicegroupmembers.deviceID
     *
     * @param deviceid the value for c_devicegroupmembers.deviceID
     * @mbggenerated
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid == null ? null : deviceid.trim();
    }
}