package com.fairyland.xrobot.modular.xrobot.domain;

public class Dict extends BaseEntity {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_dict.max_add_group_value
     *
     * @mbggenerated
     */
    private Integer maxAddGroupValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_dict.max_search_key_value
     *
     * @mbggenerated
     */
    private Integer maxSearchKeyValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_dict.max_task_interval_value
     *
     * @mbggenerated
     */
    private Integer maxTaskIntervalValue;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_dict.max_add_group_value
     *
     * @return the value of c_dict.max_add_group_value
     * @mbggenerated
     */
    public Integer getMaxAddGroupValue() {
        return maxAddGroupValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_dict.max_add_group_value
     *
     * @param maxAddGroupValue the value for c_dict.max_add_group_value
     * @mbggenerated
     */
    public void setMaxAddGroupValue(Integer maxAddGroupValue) {
        this.maxAddGroupValue = maxAddGroupValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_dict.max_search_key_value
     *
     * @return the value of c_dict.max_search_key_value
     * @mbggenerated
     */
    public Integer getMaxSearchKeyValue() {
        return maxSearchKeyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_dict.max_search_key_value
     *
     * @param maxSearchKeyValue the value for c_dict.max_search_key_value
     * @mbggenerated
     */
    public void setMaxSearchKeyValue(Integer maxSearchKeyValue) {
        this.maxSearchKeyValue = maxSearchKeyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_dict.max_task_interval_value
     *
     * @return the value of c_dict.max_task_interval_value
     * @mbggenerated
     */
    public Integer getMaxTaskIntervalValue() {
        return maxTaskIntervalValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_dict.max_task_interval_value
     *
     * @param maxTaskIntervalValue the value for c_dict.max_task_interval_value
     * @mbggenerated
     */
    public void setMaxTaskIntervalValue(Integer maxTaskIntervalValue) {
        this.maxTaskIntervalValue = maxTaskIntervalValue;
    }
}