package com.fairyland.xrobot.modular.xrobot.domain;

public class Groupnameinfo extends BaseEntity {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_groupnameinfo.groupname
     *
     * @mbggenerated
     */
    private String groupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_groupnameinfo.keyword
     *
     * @mbggenerated
     */
    private String keyword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_groupnameinfo.groupname
     *
     * @return the value of c_groupnameinfo.groupname
     * @mbggenerated
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_groupnameinfo.groupname
     *
     * @param groupname the value for c_groupnameinfo.groupname
     * @mbggenerated
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_groupnameinfo.keyword
     *
     * @return the value of c_groupnameinfo.keyword
     * @mbggenerated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_groupnameinfo.keyword
     *
     * @param keyword the value for c_groupnameinfo.keyword
     * @mbggenerated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }
}