package com.fairyland.xrobot.modular.xrobot.domain;

import com.fairyland.xrobot.modular.xrobot.utils.Utility;

public class SummaryJoinGroups extends BaseEntity {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_summaryjoingroups.taskID
     *
     * @mbggenerated
     */
    private String taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_summaryjoingroups.taskclass
     *
     * @mbggenerated
     */
    private String taskclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_summaryjoingroups.batch
     *
     * @mbggenerated
     */
    private Integer batch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_summaryjoingroups.deviceID
     *
     * @mbggenerated
     */
    private String deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_summaryjoingroups.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_summaryjoingroups.keywords
     *
     * @mbggenerated
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_summaryjoingroups.pass
     *
     * @mbggenerated
     */
    private Integer pass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_summaryjoingroups.wait
     *
     * @mbggenerated
     */
    private Integer wait;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_summaryjoingroups.taskID
     *
     * @return the value of c_summaryjoingroups.taskID
     * @mbggenerated
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_summaryjoingroups.taskID
     *
     * @param taskid the value for c_summaryjoingroups.taskID
     * @mbggenerated
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_summaryjoingroups.taskclass
     *
     * @return the value of c_summaryjoingroups.taskclass
     * @mbggenerated
     */
    public String getTaskclass() {
        return taskclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_summaryjoingroups.taskclass
     *
     * @param taskclass the value for c_summaryjoingroups.taskclass
     * @mbggenerated
     */
    public void setTaskclass(String taskclass) {
        this.taskclass = taskclass == null ? null : taskclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_summaryjoingroups.batch
     *
     * @return the value of c_summaryjoingroups.batch
     * @mbggenerated
     */
    public Integer getBatch() {
        return batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_summaryjoingroups.batch
     *
     * @param batch the value for c_summaryjoingroups.batch
     * @mbggenerated
     */
    public void setBatch(Integer batch) {
        this.batch = batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_summaryjoingroups.deviceID
     *
     * @return the value of c_summaryjoingroups.deviceID
     * @mbggenerated
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_summaryjoingroups.deviceID
     *
     * @param deviceid the value for c_summaryjoingroups.deviceID
     * @mbggenerated
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid == null ? null : deviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_summaryjoingroups.phone
     *
     * @return the value of c_summaryjoingroups.phone
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_summaryjoingroups.phone
     *
     * @param phone the value for c_summaryjoingroups.phone
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_summaryjoingroups.keywords
     *
     * @return the value of c_summaryjoingroups.keywords
     * @mbggenerated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_summaryjoingroups.keywords
     *
     * @param keywords the value for c_summaryjoingroups.keywords
     * @mbggenerated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_summaryjoingroups.pass
     *
     * @return the value of c_summaryjoingroups.pass
     * @mbggenerated
     */
    public Integer getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_summaryjoingroups.pass
     *
     * @param pass the value for c_summaryjoingroups.pass
     * @mbggenerated
     */
    public void setPass(Integer pass) {
        this.pass = pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_summaryjoingroups.wait
     *
     * @return the value of c_summaryjoingroups.wait
     * @mbggenerated
     */
    public Integer getWait() {
        return wait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_summaryjoingroups.wait
     *
     * @param wait the value for c_summaryjoingroups.wait
     * @mbggenerated
     */
    public void setWait(Integer wait) {
        this.wait = wait;
    }

    private String taskclassName;

    public String getTaskclassName() {
        return Utility.getTaskClassName(getTaskclass());
    }

    public void setTaskclassName(String taskclassName) {
        this.taskclassName = taskclassName;
    }
}