package com.fairyland.xrobot.modular.xrobot.domain;

public class TaskDict extends BaseEntity {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_taskdict.taskclass
     *
     * @mbggenerated
     */
    private String taskclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_taskdict.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_taskdict.taskclass
     *
     * @return the value of c_taskdict.taskclass
     * @mbggenerated
     */
    public String getTaskclass() {
        return taskclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_taskdict.taskclass
     *
     * @param taskclass the value for c_taskdict.taskclass
     * @mbggenerated
     */
    public void setTaskclass(String taskclass) {
        this.taskclass = taskclass == null ? null : taskclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_taskdict.name
     *
     * @return the value of c_taskdict.name
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_taskdict.name
     *
     * @param name the value for c_taskdict.name
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}