package com.fairyland.xrobot.modular.xrobot.domain;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class TaskDevices extends BaseEntity {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_taskdevices.taskID
     *
     * @mbggenerated
     */
    private String taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_taskdevices.deviceID
     *
     * @mbggenerated
     */
    private String deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_taskdevices.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_taskdevices.error
     *
     * @mbggenerated
     */
    private Integer error;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_taskdevices.errorMsg
     *
     * @mbggenerated
     */
    private String errormsg;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_taskdevices.taskID
     *
     * @return the value of c_taskdevices.taskID
     * @mbggenerated
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_taskdevices.taskID
     *
     * @param taskid the value for c_taskdevices.taskID
     * @mbggenerated
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_taskdevices.deviceID
     *
     * @return the value of c_taskdevices.deviceID
     * @mbggenerated
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_taskdevices.deviceID
     *
     * @param deviceid the value for c_taskdevices.deviceID
     * @mbggenerated
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid == null ? null : deviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_taskdevices.state
     *
     * @return the value of c_taskdevices.state
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_taskdevices.state
     *
     * @param state the value for c_taskdevices.state
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_taskdevices.error
     *
     * @return the value of c_taskdevices.error
     * @mbggenerated
     */
    public Integer getError() {
        return error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_taskdevices.error
     *
     * @param error the value for c_taskdevices.error
     * @mbggenerated
     */
    public void setError(Integer error) {
        this.error = error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_taskdevices.errorMsg
     *
     * @return the value of c_taskdevices.errorMsg
     * @mbggenerated
     */
    public String getErrormsg() {
        return errormsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_taskdevices.errorMsg
     *
     * @param errormsg the value for c_taskdevices.errorMsg
     * @mbggenerated
     */
    public void setErrormsg(String errormsg) {
        this.errormsg = errormsg == null ? null : errormsg.trim();
    }


    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date starttime;

    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date endtime;

    private Integer batch;

    public Integer getBatch() {
        return batch;
    }

    public void setBatch(Integer batch) {
        this.batch = batch;
    }

    public Date getStarttime() {
        return starttime;
    }

    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    public Date getEndtime() {
        return endtime;
    }

    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
}