package com.fairyland.xrobot.modular.xrobot.domain;

public class Wsurls extends BaseEntity {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wsurls.groupname
     *
     * @mbggenerated
     */
    private String groupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wsurls.groupname1
     *
     * @mbggenerated
     */
    private String groupname1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wsurls.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wsurls.keyword
     *
     * @mbggenerated
     */
    private String keyword;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wsurls.groupname
     *
     * @return the value of c_wsurls.groupname
     * @mbggenerated
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wsurls.groupname
     *
     * @param groupname the value for c_wsurls.groupname
     * @mbggenerated
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wsurls.groupname1
     *
     * @return the value of c_wsurls.groupname1
     * @mbggenerated
     */
    public String getGroupname1() {
        return groupname1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wsurls.groupname1
     *
     * @param groupname1 the value for c_wsurls.groupname1
     * @mbggenerated
     */
    public void setGroupname1(String groupname1) {
        this.groupname1 = groupname1 == null ? null : groupname1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wsurls.url
     *
     * @return the value of c_wsurls.url
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wsurls.url
     *
     * @param url the value for c_wsurls.url
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wsurls.keyword
     *
     * @return the value of c_wsurls.keyword
     * @mbggenerated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wsurls.keyword
     *
     * @param keyword the value for c_wsurls.keyword
     * @mbggenerated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }
}