package com.fairyland.xrobot.modular.xrobot.domain;

public class Wsusernumbers extends BaseEntity {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wsusernumbers.taskID
     *
     * @mbggenerated
     */
    private String taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wsusernumbers.taskclass
     *
     * @mbggenerated
     */
    private String taskclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wsusernumbers.batch
     *
     * @mbggenerated
     */
    private Integer batch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wsusernumbers.deviceID
     *
     * @mbggenerated
     */
    private String deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wsusernumbers.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wsusernumbers.groupname
     *
     * @mbggenerated
     */
    private String groupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wsusernumbers.groupname1
     *
     * @mbggenerated
     */
    private String groupname1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wsusernumbers.usernumber
     *
     * @mbggenerated
     */
    private String usernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wsusernumbers.keywords
     *
     * @mbggenerated
     */
    private String keywords;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wsusernumbers.taskID
     *
     * @return the value of c_wsusernumbers.taskID
     * @mbggenerated
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wsusernumbers.taskID
     *
     * @param taskid the value for c_wsusernumbers.taskID
     * @mbggenerated
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wsusernumbers.taskclass
     *
     * @return the value of c_wsusernumbers.taskclass
     * @mbggenerated
     */
    public String getTaskclass() {
        return taskclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wsusernumbers.taskclass
     *
     * @param taskclass the value for c_wsusernumbers.taskclass
     * @mbggenerated
     */
    public void setTaskclass(String taskclass) {
        this.taskclass = taskclass == null ? null : taskclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wsusernumbers.batch
     *
     * @return the value of c_wsusernumbers.batch
     * @mbggenerated
     */
    public Integer getBatch() {
        return batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wsusernumbers.batch
     *
     * @param batch the value for c_wsusernumbers.batch
     * @mbggenerated
     */
    public void setBatch(Integer batch) {
        this.batch = batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wsusernumbers.deviceID
     *
     * @return the value of c_wsusernumbers.deviceID
     * @mbggenerated
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wsusernumbers.deviceID
     *
     * @param deviceid the value for c_wsusernumbers.deviceID
     * @mbggenerated
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid == null ? null : deviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wsusernumbers.phone
     *
     * @return the value of c_wsusernumbers.phone
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wsusernumbers.phone
     *
     * @param phone the value for c_wsusernumbers.phone
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wsusernumbers.groupname
     *
     * @return the value of c_wsusernumbers.groupname
     * @mbggenerated
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wsusernumbers.groupname
     *
     * @param groupname the value for c_wsusernumbers.groupname
     * @mbggenerated
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wsusernumbers.groupname1
     *
     * @return the value of c_wsusernumbers.groupname1
     * @mbggenerated
     */
    public String getGroupname1() {
        return groupname1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wsusernumbers.groupname1
     *
     * @param groupname1 the value for c_wsusernumbers.groupname1
     * @mbggenerated
     */
    public void setGroupname1(String groupname1) {
        this.groupname1 = groupname1 == null ? null : groupname1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wsusernumbers.usernumber
     *
     * @return the value of c_wsusernumbers.usernumber
     * @mbggenerated
     */
    public String getUsernumber() {
        return usernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wsusernumbers.usernumber
     *
     * @param usernumber the value for c_wsusernumbers.usernumber
     * @mbggenerated
     */
    public void setUsernumber(String usernumber) {
        this.usernumber = usernumber == null ? null : usernumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wsusernumbers.keywords
     *
     * @return the value of c_wsusernumbers.keywords
     * @mbggenerated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wsusernumbers.keywords
     *
     * @param keywords the value for c_wsusernumbers.keywords
     * @mbggenerated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }
}